robonomics:
  seed: face ridge rookie brick aerobic medal catch goddess beauty eager bomb ribbon
  twin_id: 0
westmint:
  seed: quit before surprise inhale harvest under churn mail code light pistol immune
  endpoint: wss://westmint-rpc.polkadot.io
  token_id: 482
  collection_id: 482

service:
  interval: 60
